(integer) @integer
(float) @float
(boolean) @boolean
(text) @text
(string) @string
(jinja_comment) @comment
(identifier) @identifier
(operator) @operator
(keyword) @keyword
(statement_begin) @punctuation.special
(statement_end) @punctuation.special
(expression_begin) @punctuation.special
(expression_end) @punctuation.special
